// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOcTkUJLOpZ3j5G9C0sDM8Ctt7oNBbilQ',
    appId: '1:398710135839:web:3a7b63299a72a32539c92a',
    messagingSenderId: '398710135839',
    projectId: 'flutter-rpg-audiodrama',
    authDomain: 'flutter-rpg-audiodrama.firebaseapp.com',
    storageBucket: 'flutter-rpg-audiodrama.firebasestorage.app',
    measurementId: 'G-ZWV6E05ZSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfPd7ML5ELokCVV7QHLYOKyHtdOnq_6ck',
    appId: '1:398710135839:android:683f03be03f4ed7439c92a',
    messagingSenderId: '398710135839',
    projectId: 'flutter-rpg-audiodrama',
    storageBucket: 'flutter-rpg-audiodrama.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBezpp77O9H2XhRB8ymiwcWQGrvUHWJTRM',
    appId: '1:398710135839:ios:43499a44b70781bc39c92a',
    messagingSenderId: '398710135839',
    projectId: 'flutter-rpg-audiodrama',
    storageBucket: 'flutter-rpg-audiodrama.firebasestorage.app',
    iosClientId: '398710135839-i8847mfj6b34vn00kauha6svjrjua6us.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRpgAudiodrama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBezpp77O9H2XhRB8ymiwcWQGrvUHWJTRM',
    appId: '1:398710135839:ios:43499a44b70781bc39c92a',
    messagingSenderId: '398710135839',
    projectId: 'flutter-rpg-audiodrama',
    storageBucket: 'flutter-rpg-audiodrama.firebasestorage.app',
    iosClientId: '398710135839-i8847mfj6b34vn00kauha6svjrjua6us.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRpgAudiodrama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOcTkUJLOpZ3j5G9C0sDM8Ctt7oNBbilQ',
    appId: '1:398710135839:web:091f5ce19bf0d3c939c92a',
    messagingSenderId: '398710135839',
    projectId: 'flutter-rpg-audiodrama',
    authDomain: 'flutter-rpg-audiodrama.firebaseapp.com',
    storageBucket: 'flutter-rpg-audiodrama.firebasestorage.app',
    measurementId: 'G-RZDGE5KPJJ',
  );
}
